name = "farallon"
compatibility_date = "2023-12-01"
main = "src/index.ts"
minify = true

[vars]
DOMAIN = "https://4op.top"
PAGESIZE = 10

[[kv_namespaces]]
binding = "FARALLON"
id = "2226d0bec61343958816707ecaae68e0"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "fatesinger"

[[d1_databases]]
binding = "DB"
database_name = "hugo-cf-d1"
database_id = "8f5473ec-bb8e-407e-be59-750074cd10ab"

# [ai]
# binding = "AI"
