name = "hugo-cf-work-2"
compatibility_date = "2023-12-01"
main = "src/index.ts"
minify = true

[vars]
DOMAIN = "https://bigfa.github.io"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "hugo-cf-d1"
database_id = "81e23e8a-3b26-4025-acf8-1123bfd5af74"

# [ai]
# binding = "AI"